language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel  
before_install:
  - tlmgr install index
r_packages:
 - stats
 - rmarkdown
 - knitr
 - devtools
 - grDevices
 - jsonlite
 - reshape
apt_packages:
  - libxml2-dev
warnings_are_errors: false
