language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel  
before_install:
  - tlmgr install index
github_packages:
  - devtools
r_packages:
 - stats
 - rmarkdown
 - knitr
 - devtools
 - grDevices
 - jsonlite
 - reshape
addons:
  apt:
    packages:
      - libxml2-dev
warnings_are_errors: false
after_success:
  - Rscript -e 'covr::codecov()'
