#' Wuppertal Fiscal Data extracted from Open Spending API
#' 
#' @description 
#' ...
#' \itemize{
#'   \item The year ...
#'   \item The ....
#'   \item The ...
#'   \item The ...
#'   \item The ...
#'   }
#' 
#' @format A link with the json format data
#' @name openspending_Wuppertal
#' @source OpenSpending
#' 
#' 
NULL